# using image centos
FROM centos:7
#using variable Docker
ENV container docker

#remove files of security systemd, this files need remove because not is possible start the httpd automatic case no remove this files
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

#create the volume cgrpu
VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
