version: "3.7"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 4dmin
    ports:
      - 27017:27017

  app-node:
    image: app-node
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: DOCKER
      NODE_INSTANCE: ''
    ports:
      - 4000:4000
    command: sh -c "npm run start"
