version: "3.7"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 4dmin
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - 5672:5672
      - 15672:15672

  app-node:
    image: app-node
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
    environment:
      NODE_ENV: DOCKER
      NODE_INSTANCE: ''
    ports:
      - 4000:5000
      - 9229:9229
    command: sh -c "./wait-for db:27017 -- ./wait-for rabbitmq:5672 -- npm run dev-debug"
