name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkoutVars:
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo "Hello World"
  scanImage:
    runs-on: ubuntu-latest
    env:
      workdirScripts: ./scripts
      wordirDockerfile: ./httpd 
    steps:
      - uses: actions/checkout@v2
      - name: installDockerScan
        run: curl -L https://download.docker.com/linux/ubuntu/dists/hirsute/pool/stable/amd64/docker-scan-plugin_0.7.0~ubuntu-hirsute_amd64.deb -o docker-scan.deb
      - name: listDirectory
        run: ls -lah
      - name: installpackage
        run: sudo dpkg -i docker-scan.deb
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.orange }}"
      - name: Build and Scan Image
        # You may pin to the exact commit or the version.
        # uses: ISID/build-and-scan-image@0c59f016680e6431d462705aac334dd39b97e277
        uses: ISID/build-and-scan-image@v0.1.2
        with:
          # Image name and optionally tag in "name:tag" format
          tag: http:$(date +%s)
          # Path to base directory to run `docker build` command (default ".")
          path: httpd/
          # Path to Dockerfile, which is relative path from "path" parameter (default "Dockerfile")
          dockerfile: Dockerfile
          docker-scan-enable: true
          if: github.event.check_suite.conclusion == 'sucess'
          run: echo "Result build by color ${{ steps.random-color-generator.outputs.green }}"