name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkoutVars:
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo "Hello World"
  installPackages:
    runs-on: ubuntu-latest
    env:
      workdirScripts: ./scripts
      wordirDockerfile: ./httpd 
    steps:
      - uses: actions/checkout@v2
      - name: installDockerScan
        run: curl -L https://download.docker.com/linux/ubuntu/dists/hirsute/pool/stable/amd64/docker-scan-plugin_0.7.0~ubuntu-hirsute_amd64.deb 
      - name: listDirectory
        run: ls -lah
      - name: installpackage
        run: dpkg -i docker-scan-plugin_0.7.0~ubuntu-hirsute_amd64.deb 
      - name: scanImage
        run: docker scan Dockerfile docker-scan:e2e
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file httpd/Dockerfile --tag http:$(date +%s)

