name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list files on directory
        run: ls -lah
      - name: Build the Docker image
        run: docker build . --file httpd/Dockerfile --tag http:$(date +%s)

  checkoutVars:
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo "Hello World"

  scanImage:
    runs-on: ubuntu-latest
    env:
      workdir: ./httpd 
    steps:
      - name: scanImage
        working-directory: ${{env.workdir}}
        run: docker scan Dockerfile docker-scan:e2e

