name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkoutVars:
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo "Hello World"
  installPackages:
    runs-on: ubuntu-latest
    env:
      workdirScripts: ./scripts
      wordirDockerfile: ./httpd 
    steps:
      - uses: actions/checkout@v2
      - name: installDockerScan
        working-directory: ${{env.workdirScripts}}
        run: bash -x install-packages.sh
      - name: scanImage
        run: docker scan Dockerfile docker-scan:e2e
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file httpd/Dockerfile --tag http:$(date +%s)
