name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkoutVars:
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo "Hello World"
  scanImage:
    runs-on: ubuntu-latest
    env:
      workdirScripts: ./scripts
      wordirDockerfile: ./httpd 
    steps:
      - uses: actions/checkout@v2
      - name: installDockerScan
        run: curl -L https://download.docker.com/linux/ubuntu/dists/hirsute/pool/stable/amd64/docker-scan-plugin_0.7.0~ubuntu-hirsute_amd64.deb -o docker-scan.deb
      - name: listDirectory
        run: ls -lah
      - name: installpackage
        run: sudo dpkg -i docker-scan.deb
      - name: scanDockerfile
        run: docker scan hello-world:latest -y
      - name: Build the Docker image
        run: docker build . --file httpd/Dockerfile --tag http:$(date +%s)
      - name: scanImageHttp
        run: docker scan http:$(date +%s)

