name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  - checkout-vars:

    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: echo 'Hello World'


  - build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list files on directory
      run: ls -lah
    - name: Build the Docker image
      run: docker build . --file httpd/Dockerfile --tag http:$(date +%s)
  
  - create-package-helm:
    run-on: ubuntu-latest
    steps:
    - name: Helm Package
      # You may pin to the exact commit or the version.
      # uses: Flydiverny/helm-package-action@38c209238e15e179e4bcfbc6caac15e9a4156f05
      uses: Flydiverny/helm-package-action@0.1.0
    
