name: Docker Build App
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  agentSO: ubuntu-latest

jobs:
  checkoutVars:
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo "Hello World"
      - name: listDirectory
        run: ls -lah
  PreparePipeline:
    runs-on: ${{env.agentSO}}
    steps:
      - uses: actions/checkout@v2
      - name: installDockerScan
        run: curl -L https://download.docker.com/linux/ubuntu/dists/hirsute/pool/stable/amd64/docker-scan-plugin_0.7.0~ubuntu-hirsute_amd64.deb -o docker-scan.deb      
      - name: installpackage
        run: sudo dpkg -i docker-scan.deb
  DockerBuild:
    runs-on: ${{env.agentSO}}
    steps:
      - name: DockerBuild
        run: docker build app-nginx/ -t mnoskoski/nodesjs-simple
      - name: ExecuteDockerScan
        run: docker scan app-nginx/Dockerfile